/*
 * AMIGA-PORT: loading splash with a progress bar.
 *
 * From window-open to the title screen the port loads mods for minutes on a
 * real-speed machine with nothing on screen. This module paints one of the
 * intro/ backgrounds (converted by build/gen_splash.py into flat 8-bit
 * chunky + palette, in two styles - modern and retro - as files in
 * data/common/splash/; only the one picked is read), overlays
 * the AmiXcom logo (index 255 = transparent), fades the palette in, fills a
 * progress bar while Mod::loadAll works through the ruleset files, and fades
 * to black in ~0.5 s when StartState hands over to the main menu.
 *
 * Palette: indices 0..3 are FIXED (black border/text, the game-like yellow
 * title bar, gadget white) so the screen furniture looks identical over
 * every background; 253 is the fixed bar fill; everything else is the
 * background's own quantised palette.
 *
 * While the splash is active sdlmini suppresses SDL_Flip and screen palette
 * pushes, so the game's own "Loading..." screen never reaches the display.
 * The game may scribble over the chunky buffer in that time; the bar band is
 * therefore restored from a private copy before every bar blit, and only the
 * bar band is converted. The picture above it stays as planar data.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <proto/graphics.h>

#include "amiga_gfx.h"

#define SPLASH_W 320
#define SPLASH_H 200
#define BAND_Y   177           /* bottom band: both bars live in here */
#define BAR_X0   8
#define BAR_X1   312
#define BAR_Y0   189
#define BAR_Y1   196
#define BAR2_Y0  179           /* second bar, drawn only while it is active */
#define BAR2_Y1  186
#define IDX_FILL  253
#define IDX_FILL2 229
#define IDX_BLACK 254

/* generated by build/gen_splash.py (amiga_splash_data.c): the logo, and how
 * many scenes each style has in data/common/splash/ */
extern const int AmigaSplashBgCount;
extern const unsigned char * const AmigaSplashLogo;

/* Options::amigaSplashStyle, set by the game before its first
 * SDL_SetVideoMode: 0 modern (default), 1 retro. */
int AmigaSplash_Style = 0;

static const char *const s_style_name[2] = { "modern", "retro" };

static int s_active;
static int s_shown;
static unsigned char *s_image;      /* private 320x200 copy */
static unsigned char s_pal[768];
static int s_percent = -1;
/* the second bar overwrites part of the picture, so its rows are kept */
static unsigned char s_bar2save[(BAR2_Y1 - BAR2_Y0) * SPLASH_W];
static int s_bar2 = -1;

int AmigaSplash_Active(void)
{
	return s_active;
}

static void set_scaled_palette(int num, int den)
{
	unsigned char tmp[768];
	int i;
	for (i = 0; i < 768; i++)
		tmp[i] = (unsigned char)((s_pal[i] * num) / den);
	amigagfx_set_palette(tmp, 0, 256);
}

static void copy_to_chunky(int y0, int y1)
{
	unsigned char *ch = (unsigned char *)amigagfx_chunky();
	const int pitch = amigagfx_pitch();
	int y;
	if (ch == NULL) return;
	for (y = y0; y < y1; y++)
		memcpy(ch + (long)y * pitch, s_image + (long)y * SPLASH_W, SPLASH_W);
}

/* Read data/common/splash/<style>_<pick>.spl straight into s_pal and s_image:
 * 'SPL1' u16 w u16 h, palette[768], pixels[w*h]. One picture in memory, only
 * while the splash is up - not all of them for the whole game, which is what
 * linking them into the executable used to cost. 0 if it is not there. */
static int load_bg(int style, int pick)
{
	char path[64];
	unsigned char hdr[8];
	FILE *f;
	int w, h, ok = 0;

	snprintf(path, sizeof path, "PROGDIR:data/common/splash/%s_%d.spl",
	         s_style_name[style & 1], pick);
	f = fopen(path, "rb");
	if (f == NULL) return 0;
	if (fread(hdr, 1, 8, f) == 8 && memcmp(hdr, "SPL1", 4) == 0) {
		w = (hdr[4] << 8) | hdr[5];
		h = (hdr[6] << 8) | hdr[7];
		if (w == SPLASH_W && h <= SPLASH_H &&
		    fread(s_pal, 1, 768, f) == 768 &&
		    fread(s_image, 1, (size_t)w * h, f) == (size_t)w * h)
			ok = 1;
	}
	fclose(f);
	return ok;
}

void AmigaSplash_Show(void)
{
	const unsigned char *logo;
	int i, pick;

	if (s_shown) return;
	s_shown = 1;
	if (AmigaSplashBgCount < 1) return;

	s_image = (unsigned char *)malloc((long)SPLASH_W * SPLASH_H);
	if (s_image == NULL) return;
	memset(s_image, IDX_BLACK, (long)SPLASH_W * SPLASH_H);

	/* beam position as the only entropy an Amiga always has at boot; the
	 * same pick is the same scene in either style */
	pick = (int)(*(volatile unsigned short *)0xdff006) % AmigaSplashBgCount;
	if (!load_bg(AmigaSplash_Style, pick) &&     /* retro files missing: */
	    !load_bg(0, pick)) {                     /* the modern picture    */
		/* no picture at all: logo and bar on black, still a progress bar */
		memset(s_image, IDX_BLACK, (long)SPLASH_W * SPLASH_H);
		memset(s_pal, 0, sizeof s_pal);
		s_pal[253 * 3 + 0] = 108; s_pal[253 * 3 + 1] = 160; s_pal[253 * 3 + 2] = 176;
		s_pal[229 * 3 + 0] = 216; s_pal[229 * 3 + 1] = 148; s_pal[229 * 3 + 2] = 56;
		s_pal[17 * 3 + 0] = 232; s_pal[17 * 3 + 1] = 216; s_pal[17 * 3 + 2] = 64;
	}

	/* logo, bottom-right, 2 px off the right edge and 2 px above the band */
	logo = AmigaSplashLogo;
	if (logo != NULL && memcmp(logo, "SPLG", 4) == 0) {
		const int lw = (logo[4] << 8) | logo[5];
		const int lh = (logo[6] << 8) | logo[7];
		if (lw <= SPLASH_W && lh <= BAND_Y) {
			const int lx = SPLASH_W - lw + 2;   /* -2: the logo has its own
			                                     * transparent border */
			const int ly = BAND_Y - lh + 2;
			const unsigned char *lp = logo + 8;
			int y, x;
			for (y = 0; y < lh; y++)
				for (x = 0; x < lw; x++, lp++)
					if (*lp != 255 &&
					    lx + x >= 0 && lx + x < SPLASH_W &&
					    ly + y >= 0 && ly + y < SPLASH_H)
						s_image[(long)(ly + y) * SPLASH_W + lx + x] = *lp;
		}
	}

	memcpy(s_bar2save, s_image + (long)BAR2_Y0 * SPLASH_W,
	       sizeof s_bar2save);

	/* palette to black, image to the screen, then fade in over ~10 frames */
	set_scaled_palette(0, 16);
	copy_to_chunky(0, SPLASH_H);
	amigagfx_blit(0, 0, SPLASH_W, SPLASH_H);
	for (i = 1; i <= 10; i++) {
		WaitTOF();
		set_scaled_palette(i, 10);
	}
	s_active = 1;
	s_percent = -1;
	/* keep the system pointer usable while the game loads */
	amigagfx_pointer_suspend(1);
	AmigaSplash_Progress(1);   /* a first sliver, so the bar visibly starts */
}

/* percent 0..100; redraws and converts only the bar band */
void AmigaSplash_Progress(int percent)
{
	int y, fillw;
	if (!s_active || s_image == NULL) return;
	if (percent < 0) percent = 0;
	if (percent > 100) percent = 100;
	if (percent <= s_percent) return;
	s_percent = percent;
	{
		/* TEMP probe: timeline of the bar, to balance segments to real time */
		extern unsigned int SDL_GetTicks(void);
		extern void SDLmini_Log(const char *msg);
		char pb[48];
		snprintf(pb, sizeof pb, "splash: %d%% at %u ms", percent, SDL_GetTicks());
		SDLmini_Log(pb);
	}

	fillw = ((BAR_X1 - BAR_X0) * percent) / 100;
	for (y = BAR_Y0; y < BAR_Y1; y++) {
		unsigned char *row = s_image + (long)y * SPLASH_W;
		memset(row + BAR_X0, IDX_FILL, fillw);
		memset(row + BAR_X0 + fillw, IDX_BLACK, (BAR_X1 - BAR_X0) - fillw);
	}
	copy_to_chunky(BAND_Y, SPLASH_H);
	amigagfx_blit(0, BAND_Y, SPLASH_W, SPLASH_H - BAND_Y);
}

/* Second progress bar, above the main one and in its own colour: the music
 * pre-render can take minutes and must not look like the load has stalled.
 * The main bar keeps its position while this runs and carries on afterwards.
 * percent 0..100; call AmigaSplash_Progress2End() when the job is done. */
void AmigaSplash_Progress2(int percent)
{
	int y, fillw;
	if (!s_active || s_image == NULL) return;
	if (percent < 0) percent = 0;
	if (percent > 100) percent = 100;
	if (percent == s_bar2) return;
	s_bar2 = percent;

	fillw = ((BAR_X1 - BAR_X0) * percent) / 100;
	for (y = BAR2_Y0; y < BAR2_Y1; y++) {
		unsigned char *row = s_image + (long)y * SPLASH_W;
		memset(row + BAR_X0, IDX_FILL2, fillw);
		memset(row + BAR_X0 + fillw, IDX_BLACK, (BAR_X1 - BAR_X0) - fillw);
	}
	copy_to_chunky(BAR2_Y0, BAR2_Y1);
	amigagfx_blit(0, BAR2_Y0, SPLASH_W, BAR2_Y1 - BAR2_Y0);
}

/* Put the picture back where the second bar was and stop drawing it. */
void AmigaSplash_Progress2End(void)
{
	if (!s_active || s_image == NULL || s_bar2 < 0) return;
	memcpy(s_image + (long)BAR2_Y0 * SPLASH_W, s_bar2save, sizeof s_bar2save);
	copy_to_chunky(BAR2_Y0, BAR2_Y1);
	amigagfx_blit(0, BAR2_Y0, SPLASH_W, BAR2_Y1 - BAR2_Y0);
	s_bar2 = -1;
}

/* fill to 100%, fade to black in ~0.5 s, release */
void AmigaSplash_End(void)
{
	int i;
	if (!s_active) return;
	AmigaSplash_Progress(100);
	for (i = 11; i >= 0; i--) {
		WaitTOF();
		WaitTOF();
		set_scaled_palette(i, 12);
	}
	s_active = 0;
	if (s_image != NULL) { free(s_image); s_image = NULL; }
	/* the game takes the display now - apply its pointer setting */
	amigagfx_pointer_suspend(0);
}
